name = "formal"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Vegas"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.27.0"

[[require]]
name = "GameTheory"
git = "https://github.com/elazarg/GameTheory"
rev = "master"

[[lean_lib]]
name = "Vegas"

[[lean_lib]]
name = "distilled"
roots = ["distilled"]
